vars: {
    d2-config: {
#         layout-engine: dagre
        layout-engine: elk
#         layout-engine: tala
    }
}

direction: down

req: {
    shape: "class"
    typ: req
    id: 0
    len: n
    msg: bin
}

res: {
    shape: "class"
    typ: res
    id: 0
    len: n
    msg: bin
}

reqres: {
    shape: sequence_diagram

    client -> server: request
    server -> client: response
}
