// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package audio

type SchemaJson []struct {
	// BlackPoint corresponds to the JSON schema field "blackPoint".
	BlackPoint float64 `json:"blackPoint"`

	// Colors corresponds to the JSON schema field "colors".
	Colors []string `json:"colors"`

	// WindowSize corresponds to the JSON schema field "windowSize".
	WindowSize int `json:"windowSize"`
}
